meta_tables:
  meta_dump_zip: '' # path to the OC Meta dump Zip file
  meta_ids_out: 'meta_ids'
  all_rows: True

openalex_works:
  inp_dir: 'openalex_dump/data/works'
  out_dir: 'openalex_tables/works'
  entity_type: 'work'
openalex_sources:
  inp_dir: 'openalex_dump/data/sources'
  out_dir: 'openalex_tables/sources'
  entity_type: 'source'


## If needed, add configs for creating the tables of other OpenAlex entity types (authors, funders, publishers, institutions) E.g.:.
#openalex_authors:
#    inp_dir: 'openalex_input/data/authors'
#    out_dir: 'output_openalex_ids/authors'
#    entity_type: 'author'


db_works_doi:
  inp_dir: 'openalex_tables/works'
  db_path: 'openalex.db'
  id_type: 'doi'
  entity_type: 'work'
db_works_pmid:
  inp_dir: 'openalex_tables/works'
  db_path: 'openalex.db'
  id_type: 'pmid'
  entity_type: 'work'
db_works_pmcid:
    inp_dir: 'openalex_tables/works'
    db_path: 'openalex.db'
    id_type: 'pmcid'
    entity_type: 'work'
db_sources_issn:
  inp_dir: 'openalex_tables/sources'
  db_path: 'openalex.db'
  id_type: 'issn'
  entity_type: 'source'
db_sources_wikidata:
  inp_dir: 'openalex_tables/sources'
  db_path: 'openalex.db'
  id_type: 'wikidata'
  entity_type: 'source'

## If needed, add config for other id and OpenAlex entity types (authors, funders, publishers, institutions) See example below.
#db_authors_orcid:
#    inp_dir: ''
#    db_path: 'openalex.db'
#    id_type: 'orcid'
#    entity_type: 'author'

mapping:
  inp_dir: 'meta_ids/primary_ents'
  db_path: 'openalex.db'
  out_dir: 'mapping_output/mapped'
  multi_mapped_dir: 'mapping_output/multi_mapped'
  non_mapped_dir: 'mapping_output/non_mapped'
  res_type_field: True
  all_rows: True
